database:
  dialect: postgres
  host: localhost
  port: 5432
  dbname: testdb
  username: admin
  password: psltest
  migration: true

extension:
  master_generator: true
  cors_enabled: false
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status}

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*