name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Run tests (assuming you have tests defined)
    - name: Run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
    - uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Determine semantic version tag
    - name: Set semantic version
      id: semver
      run: |
        VERSION=$(date +'%Y.%m.%d.%H%M%S')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          docker.io/pawandevops/cockpit-docker-images:latest
          docker.io/pawandevops/cockpit-docker-images:${{ env.VERSION }}
