name: Docker Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-docker-on-ec2:
    runs-on: ubuntu-latest
    

    steps:
      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Docker image on EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_HOST }} # Provided as a secret
        run: |
          ssh -t -o StrictHostKeyChecking=no ec2-user@${EC2_PUBLIC_IP} << 'EOF'
            echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin
            sudo docker run -d -p 8080:8080 pawandevops/cockpit-docker-images:latest
          EOF
