name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Your test steps here...

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Fetch tags
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      # Get latest tag
      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

      # Determine semantic version tag
      - name: Set semantic version
        id: semver
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      # If there's no tag associated with the commit, use the latest tag available in the GitHub repository
      - if: steps.semver.outputs.version == ''
        run: echo "::set-output name=version::${{ steps.latest_tag.outputs.tag }}"

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./path/to/Dockerfile
          push: true
          tags: |
            docker.io/pawandevops/cockpit-docker-images:latest
            docker.io/pawandevops/cockpit-docker-images:${{ steps.semver.outputs.version }}

      # Tag Docker image in GitHub repository
      - name: Tag Docker image in GitHub repository
        run: |
          docker tag pawandevops/cockpit-docker-images:${{ steps.semver.outputs.version }} docker.pkg.github.com/${{ github.repository }}/pawandevops/cockpit-docker-images:${{ steps.semver.outputs.version }}
