name: market place CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  #tags:
   # - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.3

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run Go tests (assuming you have tests defined)
      - name: Run Go tests
        run: go test ./...

      # Build Docker image for testing
      - name: Build Docker image
        run: docker build . -t test-image

      # Run Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name test-container test-image

      # Wait for the service to be ready
      - name: Wait for the service to be ready
        run: sleep 10

      # Test the health endpoint
      - name: Test health endpoint
        run: |
          response=$(curl -s http://localhost:8080/api/health)
          echo "Response: $response"
          if [ "$response" != "\"healthy\"" ]; then
            echo "Health check failed"
            exit 1
          fi

      # Stop the Docker container
      - name: Stop Docker container
        run: docker stop test-container

      # Remove the Docker container
      - name: Remove Docker container
        run: docker rm test-container

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        uses: flownative/action-docker-build@master
        with:
          tag_ref: ${{ github.ref }}
          image_name: docker.pkg.github.com/pawan-tomar/go-webapp-sample/go-webapp-sample
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      # Publish release to docker.io
      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@master
        with:
          tag_ref: ${{ github.ref }}
          tag_latest: 'yes'
          source_image_name: docker.pkg.github.com/pawan-tomar/go-webapp-sample/go-webapp-sample
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/
          target_image_name: pawandevops/go-webapp-sample
          target_registry_username: ${{ secrets.DOCKER_USERNAME }}
          target_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          target_registry_endpoint: https://index.docker.io/v1/
