name: Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Create the .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # Create a temporary file for the SSH private key
      - name: Create SSH key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/default-ec2.pem

      # Set the correct permissions for the SSH key file
      - name: Set SSH key file permissions
        run: chmod 600 ~/.ssh/default-ec2.pem

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Download Terraform state artifact
      - name: Download Terraform state
        uses: dawidd6/action-download-artifact@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Terraform Deployment
          name: terraform-state
          path: ./terraform
          if_no_artifact_found: warn

      # Check if the state file was downloaded
      - name: Check Terraform state file
        run: |
          if [ -f ./terraform/terraform.tfstate ]; then
            echo "Terraform state file downloaded."
          else
            echo "No Terraform state file found."
          fi

      # Terraform init
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ./terraform

      # Terraform apply
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          terraform apply -auto-approve \
            -var="DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
            -var="DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" \
            -var="ssh_private_key_path=~/.ssh/default-ec2.pem"
        working-directory: ./terraform

      # List files in the terraform directory for debugging
      - name: List files in terraform directory
        run: ls -la ./terraform

      # Upload Terraform state artifact
      - name: Upload Terraform state
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: ./terraform/terraform.tfstate
