name: Secrets Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Debugging: Print working directory and list files
      - name: Print working directory
        run: pwd

      - name: List root directory
        run: ls -la /

      - name: List home directory
        run: ls -la ~/

      # Create the .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # Create a temporary file for the SSH private key
      - name: Create SSH key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/default-ec2.pem

      # Set the correct permissions for the SSH key file
      - name: Set SSH key file permissions
        run: chmod 600 ~/.ssh/default-ec2.pem

      # Debugging: Verify SSH key file
      - name: Verify SSH key file
        run: ls -la ~/.ssh && cat ~/.ssh/default-ec2.pem

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform init
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Debugging: Verify Terraform files
      - name: List Terraform files
        run: ls -la ./terraform

      # Terraform apply
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          terraform apply -auto-approve \
            -var="DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
            -var="DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" \
            -var="ssh_private_key_path=~/.ssh/default-ec2.pem"
        working-directory: ./terraform
