name: Validate Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform init - Required to initialize backend and providers
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ./terraform

      # Terraform validate - Ensure configuration is valid
      - name: Terraform Validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate
        working-directory: ./terraform

  apply:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      # Create the .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # Create a temporary file for the SSH private key
      - name: Create SSH key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/default-ec2.pem

      # Set the correct permissions for the SSH key file
      - name: Set SSH key file permissions
        run: chmod 600 ~/.ssh/default-ec2.pem

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform init - Required again to ensure state is up-to-date and modules are downloaded
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ./terraform

      # Terraform apply - Apply the validated configuration
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          terraform apply -auto-approve \
            -var="DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
            -var="DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" \
            -var="ssh_private_key_path=~/.ssh/default-ec2.pem"
        working-directory: ./terraform
