name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Match version tags like 'v1.2.3'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west6
  GKE_CLUSTER: playground-394421-gke
  GKE_ZONE: europe-west6-a
  DEPLOYMENT_NAME: go-webapp
  REPOSITORY: astrafy-docker
  IMAGE: go-webapp

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/819195285046/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-actions@playground-394421.iam.gserviceaccount.com'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build and Push
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${GITHUB_SHA}" \
          --build-arg GITHUB_SHA="${GITHUB_SHA}" \
          --build-arg GITHUB_REF="${GITHUB_REF}" \
          .

        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${GITHUB_SHA}"

    # Handle git tag event to build, tag, publish, and deploy the image
    - name: Build, Tag, Publish, and Deploy on Git Tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: |-
        git_tag="${{ github.ref }}"
        image_tag="${git_tag#refs/tags/}"
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${image_tag}" \
          --build-arg GITHUB_SHA="${GITHUB_SHA}" \
          --build-arg GITHUB_REF="${GITHUB_REF}" \
          .

        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${image_tag}"

        # Update the deployment YAML file with the new image tag
        sed -i "s|IMAGE_TAG|${image_tag}|g" deployment.yml

        # Deploy the application
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/${DEPLOYMENT_NAME}
        kubectl get services -o wide

    # Handle non-git tag event to update the deployment with the latest image
    - name: Update Deployment with Latest Image
      if: github.ref == 'refs/heads/main'
      run: |-
        sed -i "s|IMAGE_TAG|${GITHUB_SHA}|g" deployment.yml

        # Deploy the application
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/${DEPLOYMENT_NAME}
        kubectl get services -o wide
